### PR TITLE
Provide an option to use miniforge instead of Miniconda.

### PR DESCRIPTION
**Pull request by LTLA**
This has an actual, proper, open-source license compared to Anaconda, which makes it a lot safer to use in commercial environments that would otherwise be restricted by Anaconda's ToS. 

This option is currently not set as the default as it is liable to break a whole bunch of downstream packages. I'd guess that BioC may want to set it as the default as the license is more in line with BioC's OSS goals, but this would require at least one release's worth of break-fixes, e.g., for all of the packages that pull from `defaults`.

### CODE REVIEW

**Comment by vjcitn** [comment]
"good to go" means bring into 3.19 at this time?

**Comment by LTLA** [comment]
Yes. As you can see, the changes should have no effect if `BASILISK_USE_MINIFORGE` is not set.

**Comment by vjcitn** [comment]
Observed to fail on windows with conda installation failed with status code '2'.

**Comment by jwokaty** [comment]
Should this be the default for Linux and macOS?

**Comment by LTLA** [comment]
Agree with the timeline. Also, whenever we make the change, Miniforge should become the default, and using Miniconda should be opt-in; this will ensure that everyone has the same settings going forward. This can be easily achieved by just modifying the `if` condition in `installConda`.

**Comment by LTLA** [comment]
FYI just switching to Miniforge is helpful but not quite enough, see rstudio/reticulate#1583

**Comment by vjcitn** [comment]
right now I don't see silent installation working on windows.

**Pull request merged**
